name: Phoenix API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      suiteXmlFile:
        description: "testng xml file set up"
        type: choice
        options: [testng.xml,smoke.xml,sanity.xml]
        default: testng.xml
        required: true
        
      
    
      
  

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Set up Java (use 17, since 14 isn’t supported by GitHub Actions)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Step 3: Verify Maven installation
      - name: Verify Maven
        run: mvn -v

      # Step 4: Build project and run tests
      - name: Build with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=${{ github.event.inputs.suiteXmlFile }}

      # Step 5: Archive test reports for visibility
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

    
