name: Phoenix API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Set up Java (use 17, since 14 isn’t supported by GitHub Actions)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Step 3: Verify Maven installation
      - name: Verify Maven
        run: mvn -v

      # Step 4: Build project and run tests
      - name: Build with Maven
        run: mvn clean test -DsuiteXmlFile=testng.xml 

      # Step 5: Archive test reports for visibility
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      # Optional: Step 6 - Upload logs (helpful for debugging failures)
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: maven-logs
          path: target/*.log
